// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}

export { }
